-- Généré par scripts/evening-sessions-sql.ts — ne pas éditer à la main.
insert into public.evening_sessions (id, ord, start_time, duration_min, kind, title_fr, title_en, theme_fr, theme_en, speakers, provisional) values
('film', 1, '18:30', 7, 'film', 'Film Polaria × L''Opinion', 'Polaria × L''Opinion film', null, null, '[]'::jsonb, false),
('introduction', 2, '18:37', 1, 'ouverture', 'Introduction', 'Introduction', null, null, '[{"name":"Rémi Godeau","role":{"fr":"Directeur de la rédaction","en":"Editorial director"},"organization":"L''Opinion"}]'::jsonb, false),
('generique', 3, '18:38', 1, 'film', 'Générique', 'Opening titles', null, null, '[]'::jsonb, false),
('presentation', 4, '18:39', 6, 'presentation', 'Présentation', 'Presentation', 'Souveraineté et IA agentique', 'Sovereignty and agentic AI', '[{"name":"Cyril de Sousa Cardoso","role":{"fr":"CEO","en":"CEO"},"organization":"Polaria"},{"name":"Rémi Godeau","role":{"fr":"Directeur de la rédaction","en":"Editorial director"},"organization":"L''Opinion"}]'::jsonb, false),
('keynote-ouverture', 5, '18:45', 10, 'keynote', 'Keynote d''ouverture', 'Opening keynote', null, null, '[{"name":"Catherine Vautrin","role":{"fr":"Ministre des Armées et des Anciens combattants","en":"Minister of the Armed Forces and Veterans"}},{"name":"Rémi Godeau","role":{"fr":"Directeur de la rédaction","en":"Editorial director"},"organization":"L''Opinion","moderator":true}]'::jsonb, false),
('les100-presentation', 6, '18:55', 5, 'les100', 'Présentation exclusive des 100 qui font l''IA en Europe', 'Exclusive presentation of the 100 shaping AI in Europe', null, null, '[{"name":"Zineb El Honsali-Abridi","role":{"fr":"Principal","en":"Principal"},"organization":"Oliver Wyman"},{"name":"Grégoire Arnould","role":{"fr":"Journaliste","en":"Journalist"},"organization":"L''Opinion"}]'::jsonb, false),
('magneto-1', 7, '19:00', 1, 'magneto', 'Magnéto 1', 'Video reel 1', 'Dataviz — Infrastructures', 'Data visualisation — Infrastructure', '[]'::jsonb, false),
('table-ronde-1', 8, '19:01', 14, 'table-ronde', 'De la promesse aux infrastructures', 'From promise to infrastructure', 'L''IA n''est plus une promesse. Elle est devenue une infrastructure stratégique de croissance, de compétitivité et de souveraineté. Signaux positifs et inquiétudes en Europe', 'AI is no longer a promise. It has become a strategic infrastructure for growth, competitiveness and sovereignty. Positive signals and concerns in Europe', '[{"name":"Raphaël Doan","role":{"fr":"Auteur","en":"Author"}},{"name":"Muriel Motte","role":{"fr":"Journaliste","en":"Journalist"},"organization":"L''Opinion","moderator":true}]'::jsonb, true),
('face-a-face-1', 9, '19:15', 10, 'face-a-face', 'Face à face : étude de cas I', 'Face to face: case study I', null, null, '[{"name":"Jessyn Katchera","role":{"fr":"Partner et Responsable de l''équipe data & analytics","en":"Partner and Head of the data & analytics team"},"organization":"Oliver Wyman"},{"name":"Sébastien Rozanes","role":{"fr":"Chief Digital, Data & AI Officer","en":"Chief Digital, Data & AI Officer"},"organization":"FDJ United"},{"name":"Rémi Godeau","role":{"fr":"Directeur de la rédaction","en":"Editorial director"},"organization":"L''Opinion","moderator":true}]'::jsonb, false),
('magneto-2', 10, '19:25', 1, 'magneto', 'Magnéto 2', 'Video reel 2', 'Dataviz — Industrialisation', 'Data visualisation — Industrialisation', '[]'::jsonb, false),
('table-ronde-2', 11, '19:26', 14, 'table-ronde', 'De l''invention à l''industrialisation', 'From invention to industrialisation', 'La compétition mondiale porte désormais moins sur la recherche que sur la capacité à passer rapidement de l''invention à l''industrialisation', 'Global competition is now less about research than about the ability to move quickly from invention to industrialisation', '[{"name":"Gautier Cloix","role":{"fr":"CEO","en":"CEO"},"organization":"H Company"},{"name":"Catherine Laurent","role":{"fr":"Journaliste","en":"Journalist"},"organization":"L''Opinion","moderator":true}]'::jsonb, true),
('les100-portraits', 12, '19:40', 5, 'les100', 'Quatre portraits des 100 qui font l''IA en Europe', 'Four portraits of the 100 shaping AI in Europe', null, null, '[{"name":"Grégoire Arnould","role":{"fr":"Journaliste","en":"Journalist"},"organization":"L''Opinion"},{"name":"Rémi Godeau","role":{"fr":"Directeur de la rédaction","en":"Editorial director"},"organization":"L''Opinion"}]'::jsonb, false),
('keynote-middle', 13, '19:45', 10, 'keynote', 'Keynote du milieu de soirée', 'Midpoint keynote', null, null, '[{"name":"Charles Gorintin","role":{"fr":"Cofondateur et CTO","en":"Co-founder and CTO"},"organization":"Alan"},{"name":"Rémi Godeau","role":{"fr":"Directeur de la rédaction","en":"Editorial director"},"organization":"L''Opinion","moderator":true}]'::jsonb, false),
('face-a-face-2', 14, '19:55', 10, 'face-a-face', 'Face à face : étude de cas II', 'Face to face: case study II', null, null, '[]'::jsonb, true),
('magneto-3', 15, '20:05', 1, 'magneto', 'Magnéto 3', 'Video reel 3', 'Dataviz — Culture', 'Data visualisation — Culture', '[]'::jsonb, false),
('table-ronde-3', 16, '20:06', 14, 'table-ronde', 'De la réaction au changement de culture', 'From reaction to cultural change', 'Concilier protection et rapidité d''exécution, financer les innovations de rupture, considérer l''innovation comme une priorité stratégique : le défi est autant culturel qu''économique', 'Reconciling protection with speed of execution, financing breakthrough innovations, treating innovation as a strategic priority: the challenge is as cultural as it is economic', '[{"name":"Louise Boucher","role":{"fr":"General partner","en":"General partner"},"organization":"Sisyphus Ventures"},{"name":"Samuel Fitoussi","role":{"fr":"Essayiste et investisseur","en":"Essayist and investor"},"organization":"FRST"},{"name":"Marc Menasé","role":{"fr":"Founding Partner","en":"Founding Partner"},"organization":"Founders Future"},{"name":"David Lacombled","role":{"fr":"Président","en":"Chairman"},"organization":"La Villa Numeris","moderator":true}]'::jsonb, false),
('keynote-cloture', 17, '20:20', 10, 'cloture', 'Keynote de clôture', 'Closing keynote', null, null, '[{"name":"Laurent Solly","role":{"fr":"COO","en":"COO"},"organization":"Advanced Machine Intelligence"},{"name":"Rémi Godeau","role":{"fr":"Directeur de la rédaction","en":"Editorial director"},"organization":"L''Opinion","moderator":true}]'::jsonb, false),
('final', 18, '20:30', 10, 'final', 'Final expérimental avec IA agentique', 'Experimental finale with agentic AI', null, null, '[{"name":"Cyril de Sousa Cardoso","role":{"fr":"CEO","en":"CEO"},"organization":"Polaria"},{"name":"Rémi Godeau","role":{"fr":"Directeur de la rédaction","en":"Editorial director"},"organization":"L''Opinion"}]'::jsonb, false),
('conclusion', 19, '20:40', 2, 'cloture', 'Conclusion', 'Conclusion', null, null, '[{"name":"Rémi Godeau","role":{"fr":"Directeur de la rédaction","en":"Editorial director"},"organization":"L''Opinion"}]'::jsonb, false)
on conflict (id) do update set ord = excluded.ord, start_time = excluded.start_time, duration_min = excluded.duration_min, kind = excluded.kind, title_fr = excluded.title_fr, title_en = excluded.title_en, theme_fr = excluded.theme_fr, theme_en = excluded.theme_en, speakers = excluded.speakers, provisional = excluded.provisional;
-- Séquences retirées du programme (ex. « ouverture-agentique » et « au-revoir » au 24/09) : supprimées,
-- sans quoi elles resteraient affichées. Refusé par la clé étrangère si une archive y est rattachée.
delete from public.evening_sessions where id not in ('film', 'introduction', 'generique', 'presentation', 'keynote-ouverture', 'les100-presentation', 'magneto-1', 'table-ronde-1', 'face-a-face-1', 'magneto-2', 'table-ronde-2', 'les100-portraits', 'keynote-middle', 'face-a-face-2', 'magneto-3', 'table-ronde-3', 'keynote-cloture', 'final', 'conclusion');
