-- Généré par scripts/evening-sessions-sql.ts — ne pas éditer à la main.
insert into public.evening_sessions (id, ord, start_time, duration_min, kind, title_fr, title_en, theme_fr, theme_en, speakers, provisional) values
('ouverture-agentique', 1, '18:30', 1, 'ouverture', 'Lancement par IA agentique', 'Launch by agentic AI', null, null, '[]'::jsonb, true),
('film', 2, '18:31', 9, 'film', 'Film Polaria × L''Opinion', 'Polaria × L''Opinion film', null, null, '[]'::jsonb, true),
('presentation', 3, '18:40', 5, 'presentation', 'Présentation', 'Presentation', 'Souveraineté et IA agentique', 'Sovereignty and agentic AI', '[{"name":"Cyril de Sousa Cardoso","role":{"fr":"CEO","en":"CEO"},"organization":"Polaria"},{"name":"Rémi Godeau","role":{"fr":"Directeur de la rédaction","en":"Editorial director"},"organization":"L''Opinion"}]'::jsonb, true),
('keynote-ouverture', 4, '18:45', 10, 'keynote', 'Keynote d''ouverture', 'Opening keynote', null, null, '[{"name":"Catherine Vautrin","role":{"fr":"Ministre des Armées et des Anciens combattants","en":"Minister of the Armed Forces and Veterans"}}]'::jsonb, true),
('les100-presentation', 5, '18:55', 5, 'les100', 'Les 100 / Présentation', 'The 100 / Introduction', null, null, '[{"name":"Grégoire Arnould","role":{"fr":"Journaliste","en":"Journalist"},"organization":"L''Opinion"},{"name":"Zineb El Honsali-Abridi","role":{"fr":"Principal","en":"Principal"},"organization":"Oliver Wyman"}]'::jsonb, true),
('magneto-1', 6, '19:00', 1, 'magneto', 'Magnéto 1 / Agent IA', 'Video reel 1 / AI agent', 'Dataviz — Infrastructures', 'Data visualisation — Infrastructure', '[]'::jsonb, true),
('table-ronde-1', 7, '19:01', 14, 'table-ronde', 'De la promesse aux infrastructures', 'From promise to infrastructure', 'L''IA n''est plus une promesse. Elle est devenue une infrastructure stratégique de croissance, de compétitivité et de souveraineté. Signaux positifs et inquiétudes en Europe', 'AI is no longer a promise. It has become a strategic infrastructure for growth, competitiveness and sovereignty. Positive signals and concerns in Europe', '[{"name":"Muriel Motte","role":{"fr":"Journaliste","en":"Journalist"},"organization":"L''Opinion","moderator":true}]'::jsonb, true),
('face-a-face-1', 8, '19:15', 10, 'face-a-face', 'Face à face : étude de cas I', 'Face to face: case study I', null, null, '[]'::jsonb, true),
('magneto-2', 9, '19:25', 1, 'magneto', 'Magnéto 2 / Agent IA', 'Video reel 2 / AI agent', 'Dataviz — Industrialisation', 'Data visualisation — Industrialisation', '[]'::jsonb, true),
('table-ronde-2', 10, '19:26', 14, 'table-ronde', 'De l''invention à l''industrialisation', 'From invention to industrialisation', 'La compétition mondiale porte désormais moins sur la recherche que sur la capacité à passer rapidement de l''invention à l''industrialisation', 'Global competition is now less about research than about the ability to move quickly from invention to industrialisation', '[{"name":"Gautier Cloix","role":{"fr":"CEO","en":"CEO"},"organization":"H Company"},{"name":"Catherine Laurent","role":{"fr":"Journaliste","en":"Journalist"},"organization":"L''Opinion","moderator":true}]'::jsonb, true),
('les100-portraits', 11, '19:40', 5, 'les100', 'Les 100 / 4 portraits', 'The 100 / 4 portraits', null, null, '[{"name":"Grégoire Arnould","role":{"fr":"Journaliste","en":"Journalist"},"organization":"L''Opinion"},{"name":"Rémi Godeau","role":{"fr":"Directeur de la rédaction","en":"Editorial director"},"organization":"L''Opinion"}]'::jsonb, true),
('keynote-middle', 12, '19:45', 10, 'keynote', 'Keynote du milieu de soirée', 'Midpoint keynote', null, null, '[{"name":"Charles Gorintin","role":{"fr":"Cofondateur et CTO","en":"Co-founder and CTO"},"organization":"Alan"}]'::jsonb, true),
('face-a-face-2', 13, '19:55', 10, 'face-a-face', 'Face à face : étude de cas II', 'Face to face: case study II', null, null, '[]'::jsonb, true),
('magneto-3', 14, '20:05', 1, 'magneto', 'Magnéto 3 / Agent IA', 'Video reel 3 / AI agent', 'Dataviz — Europe / Chine / États-Unis', 'Data visualisation — Europe / China / United States', '[]'::jsonb, true),
('table-ronde-3', 15, '20:06', 14, 'table-ronde', 'De la réaction au changement de culture', 'From reaction to cultural change', 'Concilier protection et rapidité d''exécution, financer les innovations de rupture, considérer l''innovation comme une priorité stratégique : le défi est autant culturel qu''économique', 'Reconciling protection with speed of execution, financing breakthrough innovations, treating innovation as a strategic priority: the challenge is as cultural as it is economic', '[{"name":"Samuel Fitoussi","role":{"fr":"Essayiste et investisseur","en":"Essayist and investor"},"organization":"FRST"},{"name":"Louise Boucher","role":{"fr":"General partner","en":"General partner"},"organization":"Sisyphus Ventures"},{"name":"Marc Menasé","role":{"fr":"Founding Partner","en":"Founding Partner"},"organization":"Founders Future"}]'::jsonb, true),
('keynote-cloture', 16, '20:20', 10, 'cloture', 'Keynote de clôture', 'Closing keynote', null, null, '[]'::jsonb, true),
('final', 17, '20:30', 10, 'final', 'Final expérimental avec IA agentique', 'Experimental finale with agentic AI', null, null, '[{"name":"Rémi Godeau","role":{"fr":"Directeur de la rédaction","en":"Editorial director"},"organization":"L''Opinion"},{"name":"Cyril de Sousa Cardoso","role":{"fr":"CEO","en":"CEO"},"organization":"Polaria"}]'::jsonb, true),
('au-revoir', 18, '20:40', 2, 'cloture', 'Au revoir', 'Farewell', null, null, '[{"name":"Rémi Godeau","role":{"fr":"Directeur de la rédaction","en":"Editorial director"},"organization":"L''Opinion"}]'::jsonb, true)
on conflict (id) do update set ord = excluded.ord, start_time = excluded.start_time, duration_min = excluded.duration_min, kind = excluded.kind, title_fr = excluded.title_fr, title_en = excluded.title_en, theme_fr = excluded.theme_fr, theme_en = excluded.theme_en, speakers = excluded.speakers, provisional = excluded.provisional;
