/**
 * Textes du chat avec Rémi · IA (V5, WEL-920) et, plus bas, de l'Archiviste · IA (WEL-929). Propriétaire : agent chat-ui.
 *
 * Deux familles :
 *  - l'interface (titre, boutons, étiquettes) : formulations neutres, sans « tu » ni « vous » ;
 *  - ce que le chat fait dire à Rémi sans passer par l'IA (premier message du fil, préambule du repli,
 *    attente, fin de discussion, message illisible) : écrit à son nom, donc au vouvoiement, sobre,
 *    sans opinion ni promesse, comme `src/npc/remiScript.ts`. Ces phrases sont aussi listées dans
 *    `docs/TEXTES-REMI.md` (section « Chat avec Rémi · IA ») pour la relecture de Rémi Godeau.
 *
 * `src/i18n/strings.test.ts` vérifie que chaque clé existe en FR et en EN.
 */
import { defineStrings } from '../../i18n'

export const strings = defineStrings({
  // En-tête
  title: { fr: 'Rémi · IA', en: 'Rémi · AI' },
  aiNotice: { fr: 'Réponses générées par une IA', en: 'Answers generated by an AI' },
  close: { fr: 'Fermer la discussion', en: 'Close the chat' },

  // Fil de messages
  threadLabel: { fr: 'Discussion avec Rémi', en: 'Chat with Rémi' },
  authorUser: { fr: 'Vous', en: 'You' },
  authorRemi: { fr: 'Rémi', en: 'Rémi' },
  typing: { fr: 'Rémi écrit…', en: 'Rémi is typing…' },

  // Suggestions de départ (envoyées telles quelles comme message du visiteur)
  suggestionsLabel: { fr: 'Suggestions de questions', en: 'Suggested questions' },
  suggestionHow: { fr: 'Comment ça marche ?', en: 'How does it work?' },
  suggestionWho: { fr: 'Qui sont les 100 ?', en: 'Who are the 100?' },
  suggestionArchives: { fr: 'Que sont les Archives de 2040 ?', en: 'What are the 2040 Archives?' },
  suggestionProgram: { fr: 'Le programme du 6 octobre', en: 'The October 6 program' },

  // Saisie
  inputLabel: { fr: 'Votre message à Rémi', en: 'Your message to Rémi' },
  inputPlaceholder: { fr: 'Écrire à Rémi…', en: 'Write to Rémi…' },
  inputPlaceholderEnded: { fr: 'La discussion est terminée', en: 'The chat has ended' },
  send: { fr: 'Envoyer', en: 'Send' },
  counter: { fr: '{n}/{max}', en: '{n}/{max}' },
  counterOver: { fr: '{n}/{max} : message trop long', en: '{n}/{max}: message too long' },

  // Premier message du fil : court, puisque l'accueil complet est déjà passé dans la bulle du jeu
  greeting: {
    fr: 'Bonjour ! Je suis Rémi · IA. Posez-moi vos questions sur le musée, les 100 ou la soirée.',
    en: "Hello! I'm Rémi · AI. Ask me your questions about the museum, the 100 or the evening.",
  },

  // Réponses de Rémi quand le service ne répond pas comme prévu
  fallbackPreface: { fr: 'Je vous réponds brièvement :', en: 'Let me answer briefly:' },
  rateLimited: {
    fr: 'Un instant, beaucoup de visiteurs me parlent en même temps…',
    en: 'One moment, a lot of visitors are talking to me at the same time…',
  },
  retry: { fr: 'Réessayer', en: 'Try again' },
  limitReached: {
    fr: 'Nous avons beaucoup échangé, merci pour votre curiosité. Je laisse la place aux autres visiteurs : bonne visite !',
    en: 'We have talked a lot, thank you for your curiosity. I will make room for the other visitors: enjoy your visit!',
  },
  badRequest: {
    fr: "Je n'ai pas pu lire ce message. Pouvez-vous le reformuler ?",
    en: "I couldn't read that message. Could you rephrase it?",
  },
})

/**
 * Textes propres à l'Archiviste · IA (WEL-929) : ce que le chat dit en son nom, mêmes rôles que les clés de `strings`
 * qui portent le nom de Rémi (titre, accueil, puces, saisie…) ; le reste (boutons, compteur, attente, fin de discussion)
 * est commun et vient de `strings`. Le tableau `PERSONAS` (`personas.ts`) les assemble. Personnage ENTIÈREMENT GÉNÉRÉ :
 * aucune personne réelle, donc rien à faire valider par un tiers ; comme le prompt (`api/_lib/archivistePrompt.ts`), elle
 * vouvoie le visiteur, sans opinion ni promesse ni fait sur la soirée.
 */
export const archivisteStrings = defineStrings({
  // En-tête
  title: { fr: 'Archiviste · IA', en: 'Archivist · AI' },
  aiNotice: { fr: 'Réponses générées par une IA', en: 'Answers generated by an AI' },

  // Fil de messages
  threadLabel: { fr: "Discussion avec l'Archiviste", en: 'Chat with the Archivist' },
  author: { fr: "L'Archiviste", en: 'The Archivist' },
  typing: { fr: "L'Archiviste écrit…", en: 'The Archivist is typing…' },

  // Suggestions de départ (envoyées telles quelles comme message du visiteur)
  suggestionContents: { fr: 'Que contiennent les Archives ?', en: 'What do the Archives contain?' },
  suggestionProgram: { fr: 'Le programme du 6 octobre', en: 'The October 6 program' },
  suggestionWho: { fr: 'Qui êtes-vous ?', en: 'Who are you?' },
  suggestionSaid: { fr: "Que s'est-il dit ce soir ?", en: 'What was said tonight?' },

  // Saisie
  inputLabel: { fr: "Votre message à l'Archiviste", en: 'Your message to the Archivist' },
  inputPlaceholder: { fr: "Écrire à l'Archiviste…", en: 'Write to the Archivist…' },

  // Premier message du fil : court, le visiteur vient de la saluer ou de s'approcher de son socle
  greeting: {
    fr: "Bonjour. Je suis l'Archiviste · IA, gardienne des Archives de 2040. Interrogez-moi sur les vitrines ou sur le programme du 6 octobre.",
    en: "Hello. I'm the Archivist · AI, keeper of the 2040 Archives. Ask me about the display cases or the October 6 program.",
  },

  // Préambule du repli quand le service ne répond pas (les lignes viennent de `archivistScript.ts`)
  fallbackPreface: { fr: 'Je vous réponds brièvement :', en: 'Let me answer briefly:' },
})
