/**
 * Textes du chat avec Rémi · IA (V5, WEL-920). Propriétaire : agent chat-ui.
 *
 * Deux familles :
 *  - l'interface (titre, boutons, étiquettes) : formulations neutres, sans « tu » ni « vous » ;
 *  - ce que le chat fait dire à Rémi sans passer par l'IA (premier message du fil, préambule du repli,
 *    attente, fin de discussion, message illisible) : écrit à son nom, donc au vouvoiement, sobre,
 *    sans opinion ni promesse, comme `src/npc/remiScript.ts`. Ces phrases sont aussi listées dans
 *    `docs/TEXTES-REMI.md` (section « Chat avec Rémi · IA ») pour la relecture de Rémi Godeau.
 *
 * `src/i18n/strings.test.ts` vérifie que chaque clé existe en FR et en EN.
 */
import { defineStrings } from '../../i18n'

export const strings = defineStrings({
  // En-tête
  title: { fr: 'Rémi · IA', en: 'Rémi · AI' },
  aiNotice: { fr: 'Réponses générées par une IA', en: 'Answers generated by an AI' },
  close: { fr: 'Fermer la discussion', en: 'Close the chat' },

  // Fil de messages
  threadLabel: { fr: 'Discussion avec Rémi', en: 'Chat with Rémi' },
  authorUser: { fr: 'Vous', en: 'You' },
  authorRemi: { fr: 'Rémi', en: 'Rémi' },
  typing: { fr: 'Rémi écrit…', en: 'Rémi is typing…' },

  // Suggestions de départ (envoyées telles quelles comme message du visiteur)
  suggestionsLabel: { fr: 'Suggestions de questions', en: 'Suggested questions' },
  suggestionHow: { fr: 'Comment ça marche ?', en: 'How does it work?' },
  suggestionWho: { fr: 'Qui sont les 100 ?', en: 'Who are the 100?' },
  suggestionArchives: { fr: 'Que sont les Archives de 2040 ?', en: 'What are the 2040 Archives?' },
  suggestionProgram: { fr: 'Le programme du 6 octobre', en: 'The October 6 program' },

  // Saisie
  inputLabel: { fr: 'Votre message à Rémi', en: 'Your message to Rémi' },
  inputPlaceholder: { fr: 'Écrire à Rémi…', en: 'Write to Rémi…' },
  inputPlaceholderEnded: { fr: 'La discussion est terminée', en: 'The chat has ended' },
  send: { fr: 'Envoyer', en: 'Send' },
  counter: { fr: '{n}/{max}', en: '{n}/{max}' },
  counterOver: { fr: '{n}/{max} : message trop long', en: '{n}/{max}: message too long' },

  // Premier message du fil : court, puisque l'accueil complet est déjà passé dans la bulle du jeu
  greeting: {
    fr: 'Bonjour ! Je suis Rémi · IA. Posez-moi vos questions sur le musée, les 100 ou la soirée.',
    en: "Hello! I'm Rémi · AI. Ask me your questions about the museum, the 100 or the evening.",
  },

  // Réponses de Rémi quand le service ne répond pas comme prévu
  fallbackPreface: { fr: 'Je vous réponds brièvement :', en: 'Let me answer briefly:' },
  rateLimited: {
    fr: 'Un instant, beaucoup de visiteurs me parlent en même temps…',
    en: 'One moment, a lot of visitors are talking to me at the same time…',
  },
  retry: { fr: 'Réessayer', en: 'Try again' },
  limitReached: {
    fr: 'Nous avons beaucoup échangé, merci pour votre curiosité. Je laisse la place aux autres visiteurs : bonne visite !',
    en: 'We have talked a lot, thank you for your curiosity. I will make room for the other visitors: enjoy your visit!',
  },
  badRequest: {
    fr: "Je n'ai pas pu lire ce message. Pouvez-vous le reformuler ?",
    en: "I couldn't read that message. Could you rephrase it?",
  },
})
